###Create new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "tset2@tes.ry",
  "password": "test"
}

###login
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "tset2@tes.ry",
  "password": "test"
}

###who am i
GET http://localhost:3000/auth/whoami

###signout
POST http://localhost:3000/auth/signout

###Find by id
GET http://localhost:3000/auth/1

###Find by email
GET http://localhost:3000/auth?email=wesf@tes.ry

###Delete user
DELETE http://localhost:3000/auth/4

###Update user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "wesf@tes.ry",
  "password": "test123"
}
